name: Build Python Code
on:
  workflow_dispatch: # manual run
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v6
      - name: Install Python 3.11
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install Python dependencies
        run: |
          pip install pytest
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Setup python PATH
        run: |
          echo $GITHUB_WORKSPACE
          cat $GITHUB_WORKSPACE
          echo $GITHUB_ENV
          cat $GITHUB_ENV
          echo "PYTHONPATH"=$GITHUB_WORKSPACE >> $GITHUB_ENV
          echo $GITHUB_ENV
          cat $GITHUB_ENV
      - name: Run test
        run: pytest