name: Build Python Code
on:
  workflow_dispatch: # manual run
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  UBUNTU_VERSION: 24.04 # Variable at WORKFLOW Level
jobs:
  job1:
    runs-on: ubuntu-${{env.UBUNTU_VERSION}}
    env:
      PYTHON_VERSION: 3.9 #Variable at Job Level
    steps:
      - name: Clone the repo
        uses: actions/checkout@v6
      - name: Install Python ${{env.PYTHON_VERSION}}
        uses: actions/setup-python@v6
        with:
          python-version: ${{env.PYTHON_VERSION}}
      - name: Install Python dependencies
        run: |
          pip install pytest
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Setup python PATH
        run: |
          echo $GITHUB_WORKSPACE
          echo $GITHUB_ENV
          cat $GITHUB_ENV
          echo "PYTHONPATH"=$GITHUB_WORKSPACE >> $GITHUB_ENV
          echo $GITHUB_ENV
          cat $GITHUB_ENV
      - name: Run test
        run: pytest